# Generated by Django 3.2.6 on 2021-08-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_product_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='test',
            new_name='categories',
        ),
    ]
