# Generated by Django 3.2.6 on 2021-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_delete_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_api.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_api.product')),
            ],
        ),
    ]
