# Generated by Django 3.2.6 on 2021-08-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0007_rename_productcategory_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Category',
            new_name='ProductCategories',
        ),
    ]
