# Generated by Django 3.2.6 on 2021-08-12 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0009_delete_productcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(db_table='product_category', to='store_api.Category'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_api.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_api.product')),
            ],
        ),
    ]
