# Generated by Django 3.2.6 on 2021-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0010_auto_20210812_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(db_table='store_api_product_category', to='store_api.Category'),
        ),
    ]
