# Generated by Django 3.2.6 on 2021-08-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0011_alter_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product',
            new_name='product_id',
        ),
    ]
