# Generated by Django 3.2.6 on 2021-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0012_auto_20210812_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='store_api.Category'),
        ),
    ]
